urls.py
from django.urls import path
from . import views   # 앱의 views.py를 의미

app_name='post'

urlpatterns = [
    path('', views.list, name='list'),   # 아무 것도 오지 않으면 views.list 실행    
    path('create/', views.create, name='create'),
    path('<int:id>/detail/', views.detail, name='detail'),  # 특정 게시물 1개를 클릭하면 보여줌
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('model_create/', views.model_create, name='model_create'),
    path('<int:id>/model_update', views.model_update, name='model-update'),
]
    

models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=100)
    
    def __stf__(self):
        return self.title

forms.py
from django import forms
from .models import Post
    
class PostForm(forms.Form):  # forms.Form을 상속받아 여러 기능을 구현할 수 있음
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'editable'}))   # 이것을 이용해 html 코드를 만들 수 있다
    # widget = textarea(크기 변환 가능) -> 속성으로 editable을 주니 자유롭게 글 작성 가능
    
class PostModelForm(forms.ModelForm):  # 어떤 모델을 사용하는지 파악하면 알아서 구조를 지정해줌
    class Meta:
        model = Post  # 특별한 형식 지정없이 url만 입력하면 알아서 동작함(폼 생성)
        fields= '__all__'  # models.py의 Post에서 만든 컬럼을 받아와서 자동으로 생성함

views.py
from django.shortcuts import render, redirect, resolve_url
from .forms import PostForm, PostModelForm
from .models import Post

# Create your views here.
def list(request):
    posts = Post.objects.all()
    return render(request, 'post/list.html', {'posts': posts})
    
def create(request):
    if request.method == "POST":
        # 저장로직
        form = PostForm(request.POST)  # PostForm은 html로 바꿔주는 함수
        if form.is_valid():   # 유효성 검사(필수인데 공백으로 입력하거나 중복 금지 등, 형식을 안 맞는 컬럼을 거르는 경우)
            # title = form.cleaned_data['title']  # 검증 작업을 거친 데이터를 cleaned_data로 부름
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            Post.objects.create(title=title, content=content)
            return redirect(resolve_url('post:list'))  # post에 있는 list의 이름을 가져옴
    else: # GET 방식(사용자가 값을 입력하지 않은 경우)
        # 사용자가 입력할 수 있는 폼 리턴
        form = PostForm()
    return render(request, 'post/create.html', {'form': form})
    # 저장이 될 수 있는 폼을 생성해 post/create.html로 넘김

def detail(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'post/detail.html', {'post':post})

def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect(resolve_url('post:list'))

def update(request, id):
    post = Post.objects.get(id=id)  # 기존 데이터를 넣은 공간
    if request.method == "POST":
        # 폼을 검증 후 수정, 저장하는 단계
        form = PostForm(request.POST)  # request를 통해 사용자가 입력한 정보를 담음
        if form.is_valid():  # 허용이 되는 값이 들어오면
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            # post.update(title=title, content=content)  # 기존의 post값을 수정함
            post.title = title
            post.content=content
            post.save()
            return redirect(resolve_url('post:detail', id))  # 전체 글이 아닌 개별 글을 보여주는 페이지
    else:  # get 방식
        # 기존의 데이터를 폼에 담아서 사용자에게 전달
        form = PostForm({'title':post.title, 'content':post.content})  # title과 content를 값으로 가짐
    return render(request, 'post/update.html', {'form':form, 'post':post})  # form을 담아주는 공간도 같이 넘겨야 한다
        

def model_create(request):
    if request.method == "POST":
        # 저장하는 로직    
        pass
    else:   # 폼을 보여주는 규칙
        form = PostModelForm()
    return render(request, 'post/model_create.html', {"form":form})

def model_update(request, id):
    pass

templates/post/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
</head>
<body>
    <h1>여기는 base입니다.</h1>
    <a href="{% url 'post:create' %}">글작성</a>
    {% block body_block %}
    {% endblock %}
</body>
</html>

templates/post/create.html
{% extends 'post/base.html' %}

{% block body_block %}
    <!-- 폼을 넣어야 합니다 -->
    <form action="{% url 'post:create' %}" method = "post">  <!--폴더와 주소를 연결시킴-->
        {% csrf_token %}  <!--{%는 이미 정해진 규칙, {{%는 사용자가 임의로 정한 규칙-->
        {{form}}
        <input type="submit"/>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

templates/post/detail.html
{% extends 'post/base.html' %}

{% block body_block %}
    
    <a href="{% url 'post:delete' id=post.id %}">삭제</a>
    <a href="{% url 'post:update' id=post.id %}">수정</a>
    <h1>{{post.title}}</h1>
{% autoescape off %}
    <h4>{{post.content|safe}}</h4>
    <!--그런데 문제는 html 태그도 함께 나온다-->
{% endautoescape %}
{% endblock %}

templates/post/list.html
{% extends 'post/base.html' %}

{% block body_block %}
<h1>여기는 list입니다.</h1>
    {% for post in posts %}
        <h1>{{post.title}}</h1>
        <a href="{% url 'post:detail' id=post.id %}">글보기</a>
    {% endfor %}   <!--url로 변환 -> post의 detail 이름을 가진 주소로 변환 -> id는 post.id의 값으로 변환-->
{% endblock %}     <!--id 대신 다른 변수명으로 정하면 바꿀 것-->

templates/post/model_create.html
{% extends 'post/base.html' %}

{% block body_block %}

{% endblock %}

templates/post/update.html
{% extends 'post/base.html' %}

{% block body_block %}

    <form action="{% url 'post:update' id=post.id %}" method = "post">    <!--{'post':post}가 없고 form만 넘겨주었기 때문-->
        {% csrf_token %} <!--post 방식으로 넘기기 때문에 필요-->
        {{form}}
        <input type="submit"/>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}